### PR TITLE
Lead maintainer

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Review by pgte — APPROVED** [review]
🎉

**Comment by daviddias** [comment]
@pgte you can now do your first release of this module :)

**Comment by pgte** [comment]
@diasdavid `aegir release` is failing with the error:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/jenkins/pr-merge" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:libp2p/js-peer-book.git
```

I think this happens because the master branch is protected from direct pushes. I looked through the maintainer protocol and couldn't find any reference to this... How can this work with the aegis release workflow?

**Comment by victorb** [comment]
@pgte I'm currently looking into this issue. For now you can disable the direct push protection, while we find a solution.

**Comment by pgte** [comment]
@VictorBjelkholm I don't think I have permissions to do that..

**Comment by daviddias** [comment]
ref issue https://github.com/ipfs/aegir/issues/225

**Comment by victorb** [comment]
@pgte settings have been changed, can you please try again?

**Comment by pgte** [comment]
@VictorBjelkholm tried pushing, same result.

**Comment by pgte** [comment]
All done now, released version 0.8.0.

**Pull request merged**
